spring:
  datasource:
    #配置当前要使用的数据源的操作类型
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.0.105:3306/ourhome_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: lxzz1109
    driver-class-name: com.mysql.jdbc.Driver
    # Hikari will use the above plus the following to setup connection pooling
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

# redis配置
  redis:
    host: 192.168.0.105
    port: 6379
#spring.redis.password=root #根据需要
# 连接超时时间（毫秒）
    timeout: 10000
# Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 0
# 连接池最大连接数（使用负值表示没有限制） 默认 8
    lettuce:
      pool:
        max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
# 连接池中的最大空闲连接 默认 8
        max-idle: 8
# 连接池中的最小空闲连接 默认 0
        min-idle: 0

mybatis:
  mapper-locations: classpath:com/xinlizz/oh/mapper/*.xml
  type-aliases-package: com.xinlizz.oh.dto

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql